USE [master]
GO

/****** Object:  Database [AlumniDB]    Script Date: 8/5/2014 1:58:21 PM ******/
CREATE DATABASE [AlumniDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AlumniDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AlumniDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AlumniDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AlumniDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AlumniDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AlumniDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AlumniDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AlumniDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AlumniDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AlumniDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AlumniDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AlumniDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AlumniDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AlumniDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AlumniDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AlumniDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AlumniDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AlumniDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AlumniDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AlumniDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AlumniDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AlumniDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AlumniDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AlumniDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AlumniDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AlumniDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AlumniDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AlumniDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AlumniDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AlumniDB] SET  MULTI_USER 
GO

ALTER DATABASE [AlumniDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AlumniDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AlumniDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AlumniDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AlumniDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AlumniDB] SET  READ_WRITE 
GO

