//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperienceITAlumni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endorsement
    {
        public int EndorsementID { get; set; }
        public string EndorsementOutline { get; set; }
    }
}
