//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperienceITAlumni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Member_Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string FaceBook { get; set; }
        public string Google { get; set; }
        public string Twitter { get; set; }
        public string LinkedIn { get; set; }
        public string GitHub { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string EmployerName { get; set; }
        public byte[] UserPhoto { get; set; }
    }
}
